export const NO_JARGON_RULE = `SIMPLE LANGUAGE RULE (MANDATORY): Write like you are explaining this to a smart friend who has never worked in marketing or sales. Someone with a basic level of English must be able to read this once and immediately understand it.
- Keep sentences short. One idea per sentence. Avoid stacking multiple clauses together with commas and "which"/"that".
- Use everyday words instead of business or consultant-speak. Say "get more customers" not "drive customer acquisition", say "make it easy to buy" not "streamline the conversion funnel", say "helps you" not "enables you to", say "shows" not "demonstrates" or "showcases", say "use" not "leverage" or "utilise", say "start" not "initiate", say "check" not "validate", say "build" not "cultivate" or "foster".
- No jargon, no buzzwords, no acronyms unless the acronym is more familiar than the full term (e.g. keep "SEO", "ROI", "CRM"; spell out anything less common). Say "target customers" not "ICPs", say "growth plan" not "GTM roadmap", say "outreach messages" not "touchpoint sequences".
- Avoid inflated, vague, or "impressive-sounding" phrases: no "unlock", "elevate", "empower", "seamless", "robust", "holistic", "synergy", "game-changing", "cutting-edge", "best-in-class", "paradigm".
- Prefer active voice ("we help you close more deals") over passive voice ("more deals can be closed").
- Never sacrifice accuracy for simplicity, just say the same thing in plainer words.`;

export const PERSONALISATION_RULE = `PERSONALISATION RULE (MANDATORY): Every part of this output must be personalised using the user's actual inputs. Do not generate generic or placeholder content. Specifically: Use the user's actual name where relevant. Reference their actual company name. Reference their actual industry and target geography. Reference their actual revenue range when discussing growth targets. Reference their actual goal (more leads / better conversion / brand authority). Reference their specific target customer names and pain points in all messaging. Reference their actual core offer in all strategy and outreach content. If any of these fields are available from previous steps, use them. Never write output that could apply to any generic business. It must feel written specifically for this person.`;

export const GEO_AWARENESS_RULE = `GEOGRAPHY ADAPTATION (MANDATORY): Always adapt strategy based on the ICP's target geography. Consider cultural, market, and behavioral differences. Examples: India = relationship-driven, price-sensitive, WhatsApp and LinkedIn strong, slower follow-ups, warmer tone. USA = ROI-driven, direct messaging, faster decision cycles, faster cadence. UK = formal tone, trust and credibility focus. Europe = partnerships and compliance focus. Middle East = relationship and trust heavy, referral-driven. Southeast Asia = mobile-first, social commerce aware. Australia = casual professional tone, quality-focused. If no geography is specified, use a neutral global tone. Do NOT assume any default country. Each geography must influence: channels, messaging tone, timing, platform preferences, trust signals, and buying behavior references.`;

export const BUSINESS_TYPE_RULE = `BUSINESS TYPE ADAPTATION (MANDATORY): Two separate inputs describe this business, adapt strategy based on both. "Selling To" (D2C, B2B, or Both) describes WHO the buyer is: if D2C, the buyer is an individual consumer making a personal purchase decision, often driven by emotion, impulse, lifestyle fit, and social proof rather than ROI calculations; favour channels like Instagram, TikTok, influencer and community-led marketing, reviews, and urgency-driven messaging. If B2B, the buyer is part of an organisation, the decision often involves multiple stakeholders and a longer, more rational process driven by ROI, risk reduction, and business outcomes; favour professional credibility, case studies, and channels like LinkedIn and email. If Both, blend the two based on which ICP or context is being addressed. "Business Type" (Product-based, Service-based, or Hybrid) describes WHAT is being sold: Product-based means a standardised offering bought largely as-is; Service-based means custom, relationship-heavy delivery where trust in the people matters as much as the outcome; Hybrid blends both. If either input is not specified, use a neutral, general tone for that dimension. This must influence: messaging tone, psychology, channels, and buying behavior references.`;
